import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // 'prompt', not 'autoUpdate': the app asks before reloading, because reloading under
      // someone keying in a receipt throws the half-typed form away. src/pwa/UpdateBanner
      // registers the worker and shows the prompt.
      registerType: 'prompt',
      injectRegister: null,
      includeAssets: ['favicon.svg'],
      manifest: {
        name: 'Pizza Mania Stock',
        short_name: 'PM Stock',
        description: 'ระบบบริหารสต๊อก Pizza Mania',
        theme_color: '#b91c1c',
        background_color: '#ffffff',
        display: 'standalone',
        start_url: '/',
        // Generated by `npm run icons`. The manifest used to name these two files while
        // neither existed, so an install got whatever the browser fell back to.
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
      },
    }),
  ],
})
