import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import { buildTier } from './src/lib/deployTier.ts'

// P0 preview isolation (owner, 8 Oct 2026): on Cloudflare Pages only the production branch
// (`main`) builds against the live Firebase project. Every other branch — the public `demo`,
// and every preview — builds in demo mode (browser storage only), and a Pages build that does
// not say which branch it is fails instead of guessing (src/lib/deployTier.ts). Pages sets
// CF_PAGES_BRANCH while building and, with a wrangler.toml present, takes no plain build
// variables from its dashboard — so the flag is derived here. Locally `npm run demo` sets it
// through .env.demo instead. The functions are guarded separately, by host (functions/_lib/previewGuard.ts).
const tier = buildTier(process.env)
if (tier === 'preview') process.env.VITE_DEMO_MODE = '1'
process.env.VITE_DEPLOY_TIER = tier
// The test-only emulator switch (.env.e2e) must never reach a Pages build.
if (process.env.CF_PAGES && process.env.VITE_USE_EMULATOR) throw new Error('VITE_USE_EMULATOR is for the local Playwright tests only')

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // 'prompt', not 'autoUpdate': the app asks before reloading, because reloading under
      // someone keying in a receipt throws the half-typed form away. src/pwa/UpdateBanner
      // registers the worker and shows the prompt.
      registerType: 'prompt',
      injectRegister: null,
      includeAssets: ['favicon-32.png', 'apple-touch-icon.png'],
      manifest: {
        name: 'The Inventory OS',
        // The home-screen label: phones cut anything much past twelve characters.
        short_name: 'Inventory OS',
        description: 'ระบบบริหารสต๊อก Pizza Mania และ Le Lapin',
        // Slate, matching index.html. It used to be Pizza Mania red, which tinted an
        // installed window in one of the two brands' colours whichever set of books was
        // open — and disagreed with the tab colour besides.
        theme_color: '#f1f5f9',
        background_color: '#ffffff',
        display: 'standalone',
        // The UI is Thai. Without this the manifest says lang 'en', which is what a store
        // listing or an OS app drawer reads when it decides how to render the name.
        lang: 'th',
        start_url: '/',
        // Generated by `npm run icons` from assets/app-icon.png.
        //
        // The maskable entry is its own file. It used to point at pwa-512, which is drawn
        // as a rounded tile on transparency — a launcher that crops to a circle took the
        // corners off and cut into the pizza. The maskable file is square, runs green to
        // every edge, and keeps the rabbit inside the 80% safe zone.
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: 'pwa-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
        // The supplier's page (/supplier/po/<token>) is its own entry, and /api is the server: a
        // staff phone with the app installed must not answer either from the app shell.
        navigateFallbackDenylist: [/^\/supplier\/po\//, /^\/api\//],
      },
    }),
  ],
  server: {
    watch: {
      ignored: ['**/e2e-results/**', '**/docs/evidence/**', '**/firestore-debug.log'],
    },
  },
  build: {
    rollupOptions: {
      // Two pages: the app, and the supplier's delivery-date page (supplier.html, served
      // at /supplier/po/* by public/_redirects) — a separate, small bundle with no Firebase in it.
      input: {
        main: 'index.html',
        supplier: 'supplier.html',
      },
    },
  },
})
