import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // 'prompt', not 'autoUpdate': the app asks before reloading, because reloading under
      // someone keying in a receipt throws the half-typed form away. src/pwa/UpdateBanner
      // registers the worker and shows the prompt.
      registerType: 'prompt',
      injectRegister: null,
      includeAssets: ['favicon-32.png', 'apple-touch-icon.png'],
      manifest: {
        name: 'Inventory Pzm',
        short_name: 'Inventory Pzm',
        description: 'ระบบบริหารสต๊อก Pizza Mania และ Le Lapin',
        // Slate, matching index.html. It used to be Pizza Mania red, which tinted an
        // installed window in one of the two brands' colours whichever set of books was
        // open — and disagreed with the tab colour besides.
        theme_color: '#f1f5f9',
        background_color: '#ffffff',
        display: 'standalone',
        // The UI is Thai. Without this the manifest says lang 'en', which is what a store
        // listing or an OS app drawer reads when it decides how to render the name.
        lang: 'th',
        start_url: '/',
        // Generated by `npm run icons` from assets/app-icon.png.
        //
        // The maskable entry is its own file. It used to point at pwa-512, which is drawn
        // as a rounded tile on transparency — a launcher that crops to a circle took the
        // corners off and cut into the pizza. The maskable file is square, runs green to
        // every edge, and keeps the rabbit inside the 80% safe zone.
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: 'pwa-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
      },
    }),
  ],
})
