// G25 rolling release (8 Oct 2026): what an OLD app tab (writes no `version`) and a NEW one
// (moves it by 1) may do under the strict rules and under the one-release transition rules
// (firestore.transition.rules, generated by scripts/rules-transition.mjs).
//
//   npm run test:rules
import { readFileSync } from 'node:fs'
import { afterAll, beforeAll, beforeEach, describe, test } from 'vitest'
import { assertFails, assertSucceeds, initializeTestEnvironment, type RulesTestEnvironment } from '@firebase/rules-unit-testing'
import { doc, increment, setDoc, updateDoc } from 'firebase/firestore'

const STAFF = 'uid-staff'
const now = Date.UTC(2026, 9, 8)
let strict: RulesTestEnvironment
let transition: RulesTestEnvironment

async function env(projectId: string, file: string) {
  return initializeTestEnvironment({ projectId, firestore: { rules: readFileSync(new URL(`../${file}`, import.meta.url), 'utf8'), host: '127.0.0.1', port: 8080 } })
}
async function seed(e: RulesTestEnvironment) {
  await e.clearFirestore()
  await e.withSecurityRulesDisabled(async (c) => {
    const db = c.firestore()
    await setDoc(doc(db, 'users', STAFF), { name: 'Staff', email: 's@x', role: 'staff', active: true, createdAt: now })
    // A product written before G25: no `version` at all (all of production today).
    await setDoc(doc(db, 'products', 'p1'), { id: 'p1', sku: 'S-1', name: 'FLOUR', category: 'Dry', unit: 'Kilogram', unitType: 'KG', minStock: 0, hasImage: false, active: true, createdAt: now, updatedAt: now })
  })
}
// The one product edit staff may make: state a unit rate (owner, 20 Sep 2026).
const oldTab = (e: RulesTestEnvironment) => updateDoc(doc(e.authenticatedContext(STAFF).firestore(), 'products/p1'), { unitConversions: [{ label: 'Bag', size: 25 }], updatedAt: now + 1 })
const newTab = (e: RulesTestEnvironment) => updateDoc(doc(e.authenticatedContext(STAFF).firestore(), 'products/p1'), { unitConversions: [{ label: 'Bag', size: 25 }], updatedAt: now + 1, version: increment(1) })

beforeAll(async () => {
  strict = await env('pzm-rules-strict', 'firestore.rules')
  transition = await env('pzm-rules-transition', 'firestore.transition.rules')
})
afterAll(async () => {
  await strict?.cleanup()
  await transition?.cleanup()
})

describe('rolling release of G25 (entity versions)', () => {
  beforeEach(async () => {
    await seed(strict)
    await seed(transition)
  })
  test('strict rules alone would lock old tabs out: an edit without a version is refused', async () => {
    await assertFails(oldTab(strict))
    await assertSucceeds(newTab(strict))
  })
  test('transition rules accept both an old tab and a new one', async () => {
    await assertSucceeds(oldTab(transition))
    await seed(transition)
    await assertSucceeds(newTab(transition))
  })
  test('transition rules still refuse a version moved backwards or by more than 1', async () => {
    const db = transition.authenticatedContext(STAFF).firestore()
    await assertFails(updateDoc(doc(db, 'products/p1'), { unitConversions: [], updatedAt: now + 1, version: 5 }))
    await assertFails(updateDoc(doc(db, 'products/p1'), { unitConversions: [], updatedAt: now + 1, version: -1 }))
  })
})
