// Reads scripts/Sarabun-Regular.ttf and writes src/lib/sarabunFont.ts with the base64 string.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const ttf = readFileSync(join(here, 'Sarabun-Regular.ttf'))
const b64 = ttf.toString('base64')
const out = join(here, '..', 'src', 'lib', 'sarabunFont.ts')
const content =
  '// Base64 of Sarabun-Regular.ttf (SIL OFL 1.1) for Thai text in PDF exports.\n' +
  '// Generated by scripts/gen-font.mjs — do not edit by hand.\n' +
  `export const SARABUN_BASE64 = '${b64}'\n`
writeFileSync(out, content)
console.log(`Wrote ${out} (${b64.length} base64 chars)`)
